const SUPABASE_URL='https://iffxyfyfilbkqufyemoe.supabase.co',SUPABASE_KEY='sb_publishable_W8FyZODc9qO-k7YoMVrZ0g_8poq4Uae';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let data=[],editing=null,cat=0,currentUser=null;const $=s=>document.querySelector(s),storeKey='neonhub-data';
const saveLocal=()=>localStorage.setItem(storeKey,JSON.stringify(data));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function load(){const local=JSON.parse(localStorage.getItem(storeKey)||'null');try{const [cr,lr]=await Promise.all([db.from('categories').select('id,name,sort_order').eq('user_id',currentUser.id).order('sort_order').order('created_at'),db.from('links').select('id,category,title,url,sort_order').eq('user_id',currentUser.id).order('sort_order').order('created_at')]);if(cr.error||lr.error)throw Error();const lm={};lr.data.forEach(r=>(lm[r.category]??=[]).push(r));const names=[...cr.data.map(c=>c.name),...Object.keys(lm)];data=[...new Set(names)].map(name=>{const c=cr.data.find(x=>x.name===name);return {id:c?.id,name,links:lm[name]||[]}});if(!data.length){const {data:r}=await db.from('categories').insert({name:'工作',user_id:currentUser.id}).select().single();data=[{id:r?.id,name:'工作',links:[]}]}else{for(const m of data)if(!m.id){const {data:r}=await db.from('categories').insert({name:m.name,user_id:currentUser.id}).select().single();if(r)m.id=r.id}}saveLocal()}catch{data=local||[{name:'工作',links:[]}];toast('已进入本地模式，数据会保存在此浏览器')}render()}
function render(){const count=data.reduce((n,m)=>n+m.links.length,0);$('#layout').innerHTML=data.map((m,mi)=>`<section class="module" draggable="true" data-module="${mi}" ondragstart="dragModule(event,${mi})" ondragover="event.preventDefault()" ondrop="dropModule(event,${mi})"><div class="module-head"><div><h2>${esc(m.name)}</h2><span class="count">${m.links.length} 个链接</span></div><div class="module-actions"><button title="重命名" onclick="renameCat(${mi})">✎</button><button title="删除模块" onclick="removeCat(${mi})">×</button><button class="add-link" onclick="openModal(${mi})">＋ 添加</button></div></div><div class="links">${m.links.map((l,li)=>`<a class="link" draggable="true" data-link="${mi}-${li}" ondragstart="dragLink(event,${mi},${li})" ondragover="event.preventDefault()" ondrop="dropLink(event,${mi},${li})" href="${esc(l.url)}" target="_blank" rel="noopener"><span class="link-title"><span class="favicon">${esc(l.title).slice(0,1).toUpperCase()}</span>${esc(l.title)}</span><span class="link-actions"><button onclick="event.preventDefault();editLink(${mi},${li})">编辑</button><button onclick="event.preventDefault();removeLink(${mi},${li})">删除</button></span></a>`).join('')||'<div class="empty">还没有链接，添加一个常用网站吧</div>'}</div></section>`).join('');$('#summary').textContent=`${data.length} 个模块 · ${count} 个链接`}
function openModal(mi,li=null){cat=mi;editing=li;$('#modalTitle').textContent=li===null?'添加网页':'编辑网页';const l=li===null?{title:'',url:''}:data[mi].links[li];$('#title').value=l.title;$('#url').value=l.url;$('#modal').showModal();$('#title').focus()}
$('#cancelBtn').onclick=()=>$('#modal').close();$('#form').onsubmit=async e=>{e.preventDefault();let title=$('#title').value.trim(),u=$('#url').value.trim();if(!u.toLowerCase().startsWith('http://')&&!u.toLowerCase().startsWith('https://'))u='https://'+u;let m=data[cat];if(editing===null){try{const {data:r,error}=await db.from('links').insert({category:m.name,title,url:u,user_id:currentUser.id}).select().single();if(!error)m.links.push(r);else throw Error()}catch{m.links.push({id:crypto.randomUUID(),title,url:u});saveLocal()};toast('链接已添加')}else{const r=m.links[editing];try{await db.from('links').update({title,url:u}).eq('id',r.id)}catch{}Object.assign(r,{title,url:u});saveLocal();toast('链接已更新')}$('#modal').close();render()};
window.editLink=(m,l)=>openModal(m,l);window.removeLink=async(m,l)=>{if(!confirm('删除此网页？'))return;try{await db.from('links').delete().eq('id',data[m].links[l].id)}catch{}data[m].links.splice(l,1);saveLocal();render();toast('链接已删除')};window.renameCat=async i=>{const n=prompt('模块名称',data[i].name)?.trim();if(!n||n===data[i].name)return;try{for(const l of data[i].links)await db.from('links').update({category:n}).eq('id',l.id);await db.from('categories').update({name:n}).eq('id',data[i].id)}catch{}data[i].name=n;saveLocal();render()};window.removeCat=async i=>{if(data.length===1)return toast('至少保留一个模块');if(!confirm('删除此模块中的全部网页？'))return;try{for(const l of data[i].links)await db.from('links').delete().eq('id',l.id);if(data[i].id)await db.from('categories').delete().eq('id',data[i].id)}catch{}data.splice(i,1);saveLocal();render();toast('模块已删除')};$('#addCategory').onclick=async()=>{const n=prompt('新模块名称')?.trim();if(!n)return;if(data.some(m=>m.name===n))return toast('模块名称已存在');let item={name:n,links:[]};try{const {data:r,error}=await db.from('categories').insert({name:n,user_id:currentUser.id}).select().single();if(!error)item.id=r.id}catch{}data.push(item);saveLocal();render();toast('模块已创建')};async function initAuth(){const {data:{session}}=await db.auth.getSession();if(session){currentUser=session.user;document.getElementById('loginView').style.display='none';document.getElementById('account').style.display='flex';document.getElementById('userEmail').textContent=session.user.email;await load()}else{document.getElementById('account').style.display='none'}}document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const err=document.getElementById('loginError');err.textContent='';const {error}=await db.auth.signInWithPassword({email:document.getElementById('loginEmail').value.trim(),password:document.getElementById('loginPassword').value});if(error){err.textContent='登录失败：邮箱或密码不正确';return}document.getElementById('loginView').style.display='none';document.getElementById('account').style.display='flex';document.getElementById('userEmail').textContent=document.getElementById('loginEmail').value.trim();load()};document.getElementById('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};db.auth.onAuthStateChange((_event,session)=>{if(!session){document.getElementById('loginView').style.display='grid';document.getElementById('account').style.display='none'}});initAuth();


window.dragModule=(e,i)=>e.dataTransfer.setData('module',i);window.dropModule=async(e,i)=>{e.preventDefault();const from=+e.dataTransfer.getData('module');if(Number.isNaN(from)||from===i)return;const [m]=data.splice(from,1);data.splice(i,0,m);data.forEach((x,n)=>x.sort_order=n);render();for(const x of data)if(x.id)await db.from('categories').update({sort_order:x.sort_order}).eq('id',x.id);saveLocal()};window.dragLink=(e,m,l)=>e.dataTransfer.setData('link',JSON.stringify({m,l}));window.dropLink=async(e,m,l)=>{e.preventDefault();const from=JSON.parse(e.dataTransfer.getData('link')||'{}');if(from.m===undefined||from.l===undefined)return;const [x]=data[from.m].links.splice(from.l,1);if(!x)return;x.category=data[m].name;data[m].links.splice(Math.min(l,data[m].links.length),0,x);data[from.m].links.forEach((x,n)=>x.sort_order=n);data[m].links.forEach((x,n)=>x.sort_order=n);render();if(x.id)await db.from('links').update({category:data[m].name,sort_order:x.sort_order}).eq('id',x.id);for(const y of data[from.m].links)if(y.id)await db.from('links').update({sort_order:y.sort_order}).eq('id',y.id);for(const y of data[m].links)if(y.id)await db.from('links').update({sort_order:y.sort_order}).eq('id',y.id);saveLocal()};


